name: Action Test

on:
  push:
    branches:
      - develop
      - staging
      - master
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello World!"
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2
      # Pythonの環境をセットアップ
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # 依存モジュールをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest api/tests --junit-xml results/pytest.xml
        continue-on-error: true
      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.9)
          path: results/*.xml
      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml