on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - master
      - develop
    paths:
      - '**.py'

jobs:
  lint: # 任意のジョブ名
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2
      # Pythonの環境をセットアップ
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .